In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
df = pd.read_csv('/Users/purva/Desktop/Data Science Boot Camp/table_crime data_csv.csv', header = 1)

In [26]:
df.head()

City Population Violent\ncrime  \
0             Adams Village      1,861              0   
1  Addison Town and Village      2,577              3   
2             Akron Village      2,846              3   
3                    Albany     97,956            791   
4            Albion Village      6,388             23   

   Murder and\nnonnegligent\nmanslaughter  Rape\n(revised\ndefinition)1  \
0                                       0                           NaN   
1                                       0                           NaN   
2                                       0                           NaN   
3                                       8                           NaN   
4                                       0                           NaN   

  Rape\n(legacy\ndefinition)2 Robbery Aggravated\nassault Property\ncrime  \
0                           0       0                   0              12   
1                           0       0                   3              24   
2                           0       0                   3              16   
3                          30     227                 526           4,090   
4                           3       4                  16             223   

  Burglary Larceny-\ntheft Motor\nvehicle\ntheft  Arson3  Unnamed: 13  
0        2              10                     0     0.0          NaN  
1        3              20                     1     0.0          NaN  
2        1              15                     0     0.0          NaN  
3      705           3,243                   142     NaN          NaN  
4       53             165                     5     NaN          NaN

In [27]:

df.drop(['Rape\n(revised\ndefinition)1','Arson3', 'Unnamed: 13'], axis=1)

City Population Violent\ncrime  \
0                 Adams Village      1,861              0   
1      Addison Town and Village      2,577              3   
2                 Akron Village      2,846              3   
3                        Albany     97,956            791   
4                Albion Village      6,388             23   
5                Alfred Village      4,089              5   
6              Allegany Village      1,781              3   
7                  Amherst Town    118,296            107   
8            Amityville Village      9,519              9   
9                     Amsterdam     18,182             30   
10               Arcade Village      2,053              0   
11              Ardsley Village      4,523              5   
12            Asharoken Village        658              0   
13               Attica Village      2,522              2   
14                       Auburn     27,270             96   
15                 Avon Village      3,333              1   
16        Baldwinsville Village      7,473              5   
17         Ballston Spa Village      5,418              8   
18                      Batavia     15,374             57   
19                 Bath Village      5,733             15   
20                 Bedford Town     17,627              5   
21               Bethlehem Town     34,243             13   
22                   Binghamton     46,304            284   
23                  Black River      1,410              0   
24          Blooming Grove Town     12,001              8   
25              Bolivar Village      1,022              1   
26                  Bolton Town      2,325              2   
27            Boonville Village      2,054              1   
28                   Brant Town      2,065              4   
29                     Brewster      2,358              0   
..                          ...        ...            ...   
318         Tupper Lake Village      3,642              3   
319         Tuxedo Park Village        615              0   
320                 Ulster Town     12,195             14   
321                       Utica     61,686            361   
322                 Vestal Town     27,980             16   
323              Walden Village      6,887             18   
324               Wallkill Town     27,940             40   
325              Walton Village      3,012              6   
326              Warsaw Village      3,453              6   
327     Washingtonville Village      5,828              2   
328  Waterford Town and Village      8,392              4   
329            Waterloo Village      5,175             11   
330                   Watertown     28,179            109   
331                  Watervliet     10,245             26   
332        Watkins Glen Village      1,862              6   
333             Waverly Village      4,337              5   
334    Webster Town and Village     43,777             21   
335           Weedsport Village      1,797              0   
336          Wellsville Village      4,574             11   
337   Westhampton Beach Village      1,732              2   
338            West Seneca Town     44,821             35   
339           Whitehall Village      2,604              6   
340                White Plains     57,559             78   
341          Whitesboro Village      3,733              4   
342             Whitestown Town      9,141              0   
343               Woodbury Town     10,685              3   
344           Woodridge Village        829              7   
345              Woodstock Town      5,931              2   
346                     Yonkers    199,134          1,036   
347               Yorktown Town     36,643             15   

     Murder and\nnonnegligent\nmanslaughter Rape\n(legacy\ndefinition)2  \
0                                         0                           0   
1                                         0                           0   
2                  

In [28]:
df['Property\ncrime']=df['Property\ncrime'].str.replace(',','')
df['Property\ncrime']=df['Property\ncrime'].astype(int)
df['Population'] = (df['Population']).str.replace(',','')
df['Population'] = (df['Population']).astype(int)
df['Robbery'] = (df['Robbery']).str.replace(',','')
df['Robbery'] = (df['Robbery']).astype(int)
df['Larceny-\ntheft'] = (df['Larceny-\ntheft']).str.replace(',','')
df['Larceny-\ntheft'] = (df['Larceny-\ntheft']).astype(int)
df['Burglary'] = (df['Burglary']).str.replace(',','')
df['Burglary'] = (df['Burglary']).astype(int)

In [29]:
df['feature_Murder'] = df['Murder and\nnonnegligent\nmanslaughter']
df.loc[df['feature_Murder'] > 0, 'feature_Murder'] = 1

## Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
lr = LogisticRegression(C=1e9)

In [31]:
X= df[['Population','Robbery', 'Property\ncrime', 'Burglary']]
Y = df['feature_Murder']

In [35]:
model1 = lr.fit(X,Y)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [37]:
print('Coefficients')
print(model1.coef_)
print(model1.intercept_)
pred_y_sklearn = lr.predict(X)

print('\n Accuracy')
print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(lr.score(X, Y))

Coefficients
[[ 2.52576912e-05  1.83733090e-02 -1.10435520e-03  9.73278936e-03]]
[-2.49793057]

 Accuracy
feature_Murder    0   1
row_0                  
0               293  30
1                 6  19

 Percentage accuracy
0.896551724137931


## Ridge Regression

In [47]:
rr = linear_model.Ridge(alpha = 10, fit_intercept = False)
model2 = rr.fit(X,Y)
print('Coefficients')
print(model2.coef_)
print(model2.intercept_)
pred_y_sklearn = rr.predict(X)

##print('\n Accuracy')
##print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(rr.score(X, Y))

Coefficients
[ 7.52410488e-06 -3.55525250e-03 -1.60242087e-04  1.73197092e-03]
0.0

 Percentage accuracy
0.24078639344075892


## Lasso Regression

In [54]:
lass = linear_model.Lasso(alpha = 0.40)
model3 = lass.fit(X,Y)
print('Coefficients')
print(model3.coef_)
print(model3.intercept_)
pred_y_sklearn = lass.predict(X)

##print('\n Accuracy')
##print(pd.crosstab(pred_y_sklearn, Y))

print('\n Percentage accuracy')
print(lass.score(X, Y))

Coefficients
[ 5.09559540e-07 -1.80108171e-03  1.71151359e-04  4.17075728e-04]
0.0661331353878811

 Percentage accuracy
0.2136440474481144


/usr/local/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
